// The provider protocol's public surface. Importers take named symbols from here, never from the
// domain files, so a split or rename inside stays invisible to core and providers.

export {
	type BoundedChildOptions,
	type BoundedResult,
	type BoundedTimer,
	killLiveGroups,
	runBounded,
	systemTimer,
} from "./boundedChild.js";
export {
	type ChainCandidate,
	type ChainFrontier,
	type ChainWalk,
	chainAvailable,
	chainOf,
	walkChain,
} from "./chain.js";
export {
	comparePositions,
	coordinatesOf,
	type OffsetRange,
	sameRange,
	type TextCoordinates,
} from "./coordinates.js";
export {
	answerBudgetMs,
	BUDGETS,
	type Budget,
	DAEMON_CONTROLS,
	DAEMON_METHODS,
	type DaemonControl,
	type DaemonMethod,
	exclusionConfirmed,
	isDaemonMethod,
	LIFECYCLES,
	type Lifecycle,
	type LifecycleRule,
	methodMutates,
	type ReadMethod,
	type RequestOf,
	type ResponseOf,
	requestRule,
} from "./daemonMethods.js";
export {
	type DaemonLock,
	DaemonLockSchema,
	type InstallRecord,
	InstallRecordSchema,
	type InstallVersion,
	InstallVersionSchema,
	type LockRole,
	LockRoleSchema,
	parseDaemonLock,
} from "./daemonRecords.js";
export {
	ADVISORY_ISSUE_KINDS,
	type AdmittedModule,
	AdmittedModuleSchema,
	type AnswerTier,
	AnswerTierSchema,
	type ArrangeFile,
	ArrangeFileSchema,
	type ArrangePreview,
	ArrangePreviewSchema,
	type AttachedComment,
	AttachedCommentSchema,
	type CacheStats,
	CacheStatsSchema,
	type CallHierarchy,
	type CallHierarchyEdge,
	CallHierarchyEdgeSchema,
	CallHierarchySchema,
	type CoChange,
	type CoChangedWithResult,
	CoChangedWithResultSchema,
	CoChangeSchema,
	type CommentAnchor,
	CommentAnchorSchema,
	type CommentForm,
	CommentFormSchema,
	type CommentQuery,
	CommentQuerySchema,
	type CommentsResult,
	CommentsResultSchema,
	type CommitsMentioningResult,
	CommitsMentioningResultSchema,
	type CommittedFile,
	CommittedFileSchema,
	type CommittedStep,
	CommittedStepSchema,
	type ContentCounts,
	ContentCountsSchema,
	type ContentTotals,
	ContentTotalsSchema,
	type Count,
	type Counted,
	CountedSchema,
	type CountReason,
	CountReasonSchema,
	CountSchema,
	type Cycle,
	CycleSchema,
	type DescribeResult,
	DescribeResultSchema,
	type DocQuery,
	DocQuerySchema,
	type DocsResult,
	DocsResultSchema,
	type DriftedModule,
	DriftedModuleSchema,
	type EdgeGroup,
	EdgeGroupSchema,
	type EdgePeer,
	EdgePeerSchema,
	type EdgeRole,
	EdgeRoleSchema,
	ExportFactIdSchema,
	FactKindSchema,
	type FileEdits,
	FileEditsSchema,
	type FileHistory,
	type FileHistoryCommit,
	FileHistoryCommitSchema,
	FileHistorySchema,
	type FileNote,
	FileNoteSchema,
	type FileNotes,
	FileNotesSchema,
	type FindImportsResult,
	FindImportsResultSchema,
	type FoundComment,
	FoundCommentSchema,
	type FoundDoc,
	FoundDocSchema,
	type GraphSummary,
	GraphSummarySchema,
	ImportFactIdSchema,
	type ImportQuery,
	ImportQuerySchema,
	type IndexActivity,
	IndexActivitySchema,
	type IndexCause,
	IndexCauseSchema,
	type IndexOutcome,
	IndexOutcomeSchema,
	type IndexStatus,
	IndexStatusSchema,
	type InsertOutcome,
	InsertOutcomeSchema,
	type InsertPreview,
	InsertPreviewSchema,
	type KnowledgeSweep,
	KnowledgeSweepSchema,
	type LedgerMark,
	LedgerMarkSchema,
	type LiteralQuery,
	LiteralQuerySchema,
	type LiteralsResult,
	LiteralsResultSchema,
	type Mention,
	MentionSchema,
	type ModuleDeclarations,
	ModuleDeclarationsSchema,
	type ModuleFactsResult,
	ModuleFactsResultSchema,
	type ModuleStatus,
	ModuleStatusSchema,
	type MostReferencedEntry,
	MostReferencedEntrySchema,
	type MostReferencedResult,
	MostReferencedResultSchema,
	type MoveOutcome,
	MoveOutcomeSchema,
	type MovePlan,
	MovePlanSchema,
	type MovePreview,
	MovePreviewFileSchema,
	MovePreviewSchema,
	type NameTally,
	NameTallySchema,
	type OverviewResult,
	OverviewResultSchema,
	type ParseFactsResult,
	ParseFactsResultSchema,
	type Promoted,
	PromotedSchema,
	type ProviderStatus,
	ProviderStatusSchema,
	type RefactorBeforeImage,
	RefactorBeforeImageSchema,
	type RefactorCommitResult,
	RefactorCommitResultSchema,
	type RefactorIssue,
	RefactorIssueSchema,
	type RefactorNoteWriteResult,
	RefactorNoteWriteResultSchema,
	type RefactorRevertResult,
	RefactorRevertResultSchema,
	type RefactorSettledImage,
	RefactorSettledImageSchema,
	type RefactorSettlements,
	RefactorSettlementsSchema,
	type RefactorStartResult,
	RefactorStartResultSchema,
	type RefactorTrackResult,
	RefactorTrackResultSchema,
	type RefactorUndoResult,
	RefactorUndoResultSchema,
	type RefactorWriteFileResult,
	RefactorWriteFileResultSchema,
	type ReferencesResult,
	ReferencesResultSchema,
	type ReferenceUse,
	ReferenceUseSchema,
	type RenameConcern,
	RenameConcernSchema,
	type RenameEditPlan,
	RenameEditPlanSchema,
	type RenameFile,
	RenameFileSchema,
	type RenamePlan,
	RenamePlanSchema,
	type RenameStepOutcome,
	RenameStepOutcomeSchema,
	type ReplaceOutcome,
	ReplaceOutcomeSchema,
	type ReplacePreview,
	ReplacePreviewSchema,
	type ReplaceSpanOutcome,
	ReplaceSpanOutcomeSchema,
	type ReverseStep,
	ReverseStepSchema,
	type RouteEdge,
	RouteEdgeSchema,
	type RouteModule,
	RouteModuleSchema,
	type RouteState,
	RouteStateSchema,
	type ScanCounts,
	ScanCountsSchema,
	type ScopeSymbol,
	ScopeSymbolSchema,
	type ScopeSymbols,
	ScopeSymbolsSchema,
	type SearchSymbolsResult,
	SearchSymbolsResultSchema,
	type SettledFile,
	SettledFileSchema,
	type Settlement,
	SettlementSchema,
	type SharedLiteral,
	SharedLiteralSchema,
	type SharedLiteralsResult,
	SharedLiteralsResultSchema,
	type SourceReadOutcome,
	SourceReadOutcomeSchema,
	type StepBase,
	StepBaseSchema,
	type StepCancel,
	StepCancelSchema,
	type StepKind,
	StepKindSchema,
	type StepOutcome,
	StepOutcomeSchema,
	type StepPhase,
	StepPhaseSchema,
	type StoredComment,
	StoredCommentSchema,
	type StoredDeclaration,
	StoredDeclarationSchema,
	type StoredDoc,
	StoredDocSchema,
	type StoredExport,
	StoredExportSchema,
	type StoredFact,
	StoredFactSchema,
	type StoredImport,
	StoredImportSchema,
	type StoredLiteral,
	StoredLiteralSchema,
	type StoredReference,
	StoredReferenceSchema,
	type SubjectDiagnosis,
	SubjectDiagnosisSchema,
	type SymbolAtReply,
	SymbolAtReplySchema,
	type SymbolAtResult,
	SymbolAtResultSchema,
	type SymbolEdges,
	SymbolEdgesSchema,
	type SymbolSource,
	SymbolSourceSchema,
	type SymbolSummary,
	SymbolSummarySchema,
	type TransactionStatus,
	TransactionStatusSchema,
	type TransactionStep,
	TransactionStepSchema,
	type TypeHierarchy,
	TypeHierarchySchema,
	type UnreversedRebind,
	UnreversedRebindSchema,
	type UseFrom,
	UseFromSchema,
	type UsesFromResult,
	UsesFromResultSchema,
} from "./daemonShapes.js";
export {
	CLIENT_LINE_CAP,
	type ClientFrame,
	ClientFrameSchema,
	CONNECT_TIMEOUT_MS,
	DAEMON_STOPPING_MESSAGE,
	GATE_BUSY_CODE,
	GATE_WAIT_CAP_MS,
	HEARTBEAT_MISSED_LIMIT,
	HEARTBEAT_MS,
	HELLO_DEADLINE_MS,
	type HelloFrame,
	HelloFrameSchema,
	type PingFrame,
	PingFrameSchema,
	type PongFrame,
	PongFrameSchema,
	type RejectFrame,
	RejectFrameSchema,
	type RequestFrame,
	RequestFrameSchema,
	type RequestOptions,
	type ResponseFrame,
	ResponseFrameSchema,
	SERVER_LINE_CAP,
	type ServerFrame,
	ServerFrameSchema,
	WARMUP_FAILED_PREFIX,
	type WelcomeFrame,
	WelcomeFrameSchema,
} from "./daemonWire.js";
export { defined } from "./defined.js";
export { isTooDeep, MAX_NESTING, NestingGauge, saysTooDeep, TOO_DEEP } from "./depth.js";
export {
	applyEdits,
	type EditConflict,
	type EditPlan,
	planEdits,
	type TextEdit,
	TextEditSchema,
	unionOf,
} from "./edits.js";
export {
	commentFactId,
	declarationFactId,
	docFactId,
	exportFactId,
	FACT_KINDS,
	FACT_SCHEME,
	type FactId,
	type FactKind,
	factKindOf,
	factModuleOf,
	importFactId,
	isFactId,
	literalFactId,
	type OriginEdge,
	type OwnerStarts,
	ownerStarts,
	parseFactId,
	parseFactIdResult,
	referenceFactId,
} from "./factId.js";
export { hashBytes, hashContent } from "./hash.js";
export { FOLD_MARK, type HeaderFold, type HeaderSpan, renderHeader, type WorkMeter } from "./header.js";
export {
	type ImportEditsRequest,
	ImportEditsRequestSchema,
	type ImportEditsResponse,
	ImportEditsResponseSchema,
	type ImportRefusal,
	ImportRefusalSchema,
} from "./importEdits.js";
export {
	type JudgeLoadCycleAnswer,
	JudgeLoadCycleAnswerSchema,
	type JudgeLoadCycleRequest,
	JudgeLoadCycleRequestSchema,
	LoadCycleEvidenceSchema,
	type LoadCycleHazard,
	LoadCycleHazardSchema,
	LoadCycleMemberSchema,
	LoadCycleUnknownSchema,
	type ModuleCycle,
	ModuleCycleSchema,
	ModuleCyclesRequestSchema,
	ModuleProblemsRequestSchema,
	ModuleProblemsResponseSchema,
	ReleaseLoadCycleNotificationSchema,
	unjudgedLoadCycle,
} from "./loadCycles.js";
export {
	type MermaidStatement,
	type MermaidToken,
	mermaidClick,
	mermaidStatements,
	type SourceSegment,
} from "./mermaid.js";
export {
	BindRequestSchema,
	DiscoverProjectRequestSchema,
	EVENT_SCHEMAS,
	type FileContent,
	FileContentSchema,
	ForgetModuleNotificationSchema,
	InitializeRequestSchema,
	InitializeResponseSchema,
	isProviderMethod,
	METHOD_SCHEMAS,
	type ModuleAdmission,
	ModuleAdmissionNotificationSchema,
	NOTIFICATION_SCHEMAS,
	ParseFileRequestSchema,
	PROVIDER_EVENTS,
	PROVIDER_METHODS,
	PROVIDER_NOTIFICATIONS,
	type ProbeBatchRequest,
	ProbeBatchRequestSchema,
	type ProbeBatchResponse,
	ProbeBatchResponseSchema,
	ProviderErrorSchema,
	type ProviderEvent,
	type ProviderMethod,
	type ProviderNotification,
	type ProviderPhase,
	ProviderPhaseNotificationSchema,
	type ProviderTiers,
	ProviderTiersSchema,
	type ProviderWords,
	ProviderWordsSchema,
	ResolveImportRequestSchema,
	TypeOfRequestSchema,
} from "./methods.js";
export {
	compileExclusion,
	globToRegExp,
	type ModuleExclusion,
	ModuleExclusionSchema,
} from "./moduleExclusion.js";
export { ModulePathSchema } from "./modulePath.js";
export {
	type AsyncModuleStore,
	type AsyncStoreSpec,
	asyncModuleStore,
	type Entries,
	type Held,
	type Maybe,
	type ModuleStore,
	type ModuleValue,
	moduleStore,
	type Origin,
	type StoreProvider,
	type StoreSpec,
} from "./moduleStore.js";
export {
	type ArrangeAnchor,
	ArrangeAnchorSchema,
	type ArrangeEditsRequest,
	ArrangeEditsRequestSchema,
	type ArrangeImportSite,
	ArrangeImportSiteSchema,
	type ArrangeMember,
	ArrangeMemberSchema,
	type DependencyOrigin,
	DependencyOriginSchema,
	type ImportKind,
	ImportKindSchema,
	type ImportOrigin,
	ImportOriginSchema,
	MOVE_EDIT_CONFLICT,
	type MoveAnchor,
	MoveAnchorSchema,
	type MoveBlockedReason,
	MoveBlockedReasonSchema,
	type MoveBlockedSite,
	MoveBlockedSiteSchema,
	type MoveDependency,
	MoveDependencySchema,
	type MoveEditsRequest,
	MoveEditsRequestSchema,
	type MoveEditsResponse,
	MoveEditsResponseSchema,
	type MoveImportSite,
	MoveImportSiteSchema,
	type MoveRefusal,
	MoveRefusalSchema,
} from "./move.js";
export {
	type CodeFence,
	codeFences,
	type FoundRef,
	findRefLinks,
	findRefs,
	formatRef,
	type ParsedRef,
	parseRef,
	REF_SCHEME,
	type RefLink,
	type RefParse,
} from "./noteRefs.js";
export {
	ConfirmNoteRequestSchema,
	DoubtNoteRequestSchema,
	NOTE_MAX,
	type Note,
	type NoteAuthor,
	NoteAuthorSchema,
	type NoteBacklinks,
	NoteBacklinksRequestSchema,
	NoteBacklinksSchema,
	type NoteLink,
	NoteLinkSchema,
	type NoteOutcome,
	NoteOutcomeSchema,
	type NoteProposal,
	NoteProposalSchema,
	type NoteRefProblem,
	NoteRefProblemSchema,
	NoteSchema,
	ReadNoteRequestSchema,
	type RefCandidate,
	RefCandidateSchema,
	ResolveNoteProposalRequestSchema,
	type SearchRefs,
	SearchRefsRequestSchema,
	SearchRefsSchema,
	WriteNoteRequestSchema,
} from "./noteShapes.js";
export { withOccurrences } from "./occurrences.js";
export { type PaintFacts, PaintFactsSchema } from "./paint.js";
export { err, formatFailure, ok, type ParseFailure, type ParseResult, safeDigits } from "./parseResult.js";
export {
	type AllList,
	AllListSchema,
	type Certainty,
	CertaintySchema,
	type CommentSpan,
	CommentSpanSchema,
	type Conflict,
	ConflictSchema,
	type DocRegion,
	DocRegionSchema,
	type EntryHow,
	EntryHowSchema,
	type EntryRole,
	EntryRoleSchema,
	type Export,
	type ExportForm,
	ExportFormSchema,
	ExportSchema,
	type ExportTarget,
	ExportTargetSchema,
	type FileFacts,
	FileFactsSchema,
	type FileRole,
	FileRoleSchema,
	type Import,
	type ImportEdge,
	ImportEdgeSchema,
	type ImportResolution,
	ImportResolutionSchema,
	ImportSchema,
	type IndexDepth,
	IndexDepthSchema,
	type Landing,
	LandingSchema,
	type Literal,
	LiteralSchema,
	type Meaning,
	MeaningSchema,
	type ProjectModel,
	ProjectModelSchema,
	type ResolutionMode,
	ResolutionModeSchema,
	type ScopeContribution,
	ScopeContributionSchema,
	type Selector,
	SelectorSchema,
} from "./project.js";
export {
	angleDelta,
	DEFAULT_EXCLUDED_DIRECTORIES,
	discoverByWalk,
	handlersFor,
	type ProviderMethods,
	projectDiagnostic,
	qualifierDescriptors,
	type WalkOptions,
	walkWorkspace,
	workspaceFile,
	workspaceModule,
} from "./providerKit.js";
export { OPEN_READ_POLICY, type ReadPolicy, readPolicy } from "./readPolicy.js";
export {
	AnswerRelationGapRequestSchema,
	RELATION_KINDS,
	RELATION_TEXT_MAX,
	type Relation,
	type RelationBetween,
	RelationBetweenSchema,
	type RelationCandidate,
	RelationCandidateSchema,
	type RelationCandidates,
	RelationCandidatesRequestSchema,
	RelationCandidatesSchema,
	type RelationEvidence,
	RelationEvidenceSchema,
	RelationFeedbackCountsSchema,
	RelationFeedbackRequestSchema,
	RelationFeedbackResultSchema,
	type RelationGap,
	type RelationGapAnswer,
	RelationGapAnswerSchema,
	RelationGapSchema,
	type RelationGaps,
	RelationGapsRequestSchema,
	RelationGapsSchema,
	type RelationHealth,
	RelationHealthSchema,
	type RelationKind,
	RelationKindSchema,
	type RelationOutcome,
	RelationOutcomeSchema,
	type RelationParts,
	RelationPartsSchema,
	type RelationProvenance,
	RelationProvenanceSchema,
	RelationSchema,
	type RelationStatus,
	RelationStatusSchema,
	type Relations,
	RelationsBetweenRequestSchema,
	RelationsOfRequestSchema,
	RelationsSchema,
	type StatedRelation,
	StatedRelationSchema,
	WriteRelationRequestSchema,
} from "./relationShapes.js";
export {
	type BlockedSite,
	type BlockedSiteReason,
	BlockedSiteReasonSchema,
	BlockedSiteSchema,
	RENAME_EDIT_CONFLICT,
	type RenameEditsRequest,
	RenameEditsRequestSchema,
	type RenameEditsResponse,
	RenameEditsResponseSchema,
	type RenameRefusal,
	RenameRefusalSchema,
	type RenameSite,
	RenameSiteSchema,
} from "./rename.js";
export { readSwept, sourceFiles } from "./residue.js";
export {
	notImplementedBinding,
	notImplementedImport,
	notImplementedImportEdits,
	notImplementedMove,
	notImplementedType,
	type ProviderEvents,
	type ProviderHandlers,
	type ProviderNotificationHandlers,
	runProviderOnStdio,
	serveProvider,
	whenServed,
} from "./serve.js";
export { firstLineOf, shebangInterpreter } from "./shebang.js";
export { type CursorMark, type CursorSpan, SourceCursor } from "./sourceCursor.js";
export {
	MAX_SOURCE_BYTES,
	type OutsideRead,
	readWorkspaceFile,
	readWorkspaceHead,
	type SourceFileRead,
} from "./sourceFile.js";
export {
	ANONYMOUS_NAMESPACE,
	composeSymbolId,
	type Descriptor,
	type DescriptorKind,
	decodeModuleField,
	encodeModuleField,
	expectIdSpace,
	type IdField,
	isCanonicalModule,
	isLocalSymbol,
	isParameterSymbol,
	isSymbolId,
	isWithin,
	languageOf,
	moduleOf,
	normalizeModulePath,
	ownerOf,
	parseSymbolId,
	parseSymbolIdPrefix,
	parseSymbolIdResult,
	quoteName,
	readIdField,
	rebaseSymbolId,
	reverseOf,
	SYMBOL_SCHEME,
	type SymbolId,
	type SymbolIdPrefix,
	sameNameAndKind,
	spellsName,
} from "./symbolId.js";
export {
	type Contains,
	ContainsSchema,
	type Declaration,
	DeclarationSchema,
	type Diagnostic,
	DiagnosticSchema,
	GROUPING_KINDS,
	type Metrics,
	MetricsSchema,
	type Position,
	PositionSchema,
	type Range,
	RangeSchema,
	type Reference,
	type ReferenceOrigin,
	ReferenceOriginSchema,
	type ReferenceRole,
	ReferenceRoleSchema,
	ReferenceSchema,
	RUNNING_KINDS,
	type SymbolKind,
	SymbolKindSchema,
	type Visibility,
	VisibilitySchema,
} from "./symbols.js";
export {
	type Binding,
	BindingSchema,
	isResolved,
	type Provenance,
	ProvenanceSchema,
	reasonOf,
	type TypeInfo,
	TypeInfoSchema,
	type UnknownReason,
	UnknownReasonSchema,
} from "./values.js";
export {
	type Compatibility,
	checkCompatibility,
	isCompatibleProtocol,
	OLDEST_CLIENT_MAJOR,
	PROTOCOL_VERSION,
	parseVersion,
	SCHEMA_VERSION,
	servesClient,
	type Version,
} from "./version.js";
export { type Contained, type LeafMode, resolveContained } from "./workspacePath.js";
