// The provider protocol's public surface. Importers take named symbols from here, never from the
// domain files, so a split or rename inside stays invisible to core and providers.

export {
	comparePositions,
	coordinatesOf,
	type OffsetRange,
	sameRange,
	type TextCoordinates,
} from "./coordinates.js";
export { Cursor, err, formatFailure, ok, type ParseFailure, type ParseResult, safeDigits } from "./cursor.js";
export {
	type ClientFrame,
	ClientFrameSchema,
	type HelloFrame,
	HelloFrameSchema,
	type PingFrame,
	PingFrameSchema,
	type PongFrame,
	PongFrameSchema,
	type RejectFrame,
	RejectFrameSchema,
	type RequestFrame,
	RequestFrameSchema,
	type ResponseFrame,
	ResponseFrameSchema,
	type ServerFrame,
	ServerFrameSchema,
	type WelcomeFrame,
	WelcomeFrameSchema,
} from "./daemonWire.js";
export {
	applyEdits,
	type EditConflict,
	type EditPlan,
	planEdits,
	type TextEdit,
	TextEditSchema,
} from "./edits.js";
export {
	answerFactId,
	composeFactId,
	declarationFactId,
	doubtFactId,
	FACT_KINDS,
	FACT_SCHEME,
	type FactId,
	type FactKind,
	factKindOf,
	factModuleOf,
	importFactId,
	isFactId,
	literalFactId,
	parseFactId,
	parseFactIdResult,
	referenceFactId,
} from "./factId.js";
export {
	BindRequestSchema,
	DiscoverProjectRequestSchema,
	InitializeRequestSchema,
	InitializeResponseSchema,
	isProviderMethod,
	METHOD_SCHEMAS,
	ParseFileRequestSchema,
	PROVIDER_METHODS,
	ProviderErrorSchema,
	type ProviderMethod,
	type ProviderTiers,
	ProviderTiersSchema,
	ResolveImportRequestSchema,
	TypeOfRequestSchema,
} from "./methods.js";
export {
	type DependencyOrigin,
	DependencyOriginSchema,
	type ImportKind,
	ImportKindSchema,
	type ImportOrigin,
	ImportOriginSchema,
	MOVE_EDIT_CONFLICT,
	type MoveBlockedReason,
	MoveBlockedReasonSchema,
	type MoveBlockedSite,
	MoveBlockedSiteSchema,
	type MoveDependency,
	MoveDependencySchema,
	type MoveEditsRequest,
	MoveEditsRequestSchema,
	type MoveEditsResponse,
	MoveEditsResponseSchema,
	type MoveImportSite,
	MoveImportSiteSchema,
	type MoveRefusal,
	MoveRefusalSchema,
} from "./move.js";
export {
	type CommentSpan,
	CommentSpanSchema,
	type FileFacts,
	FileFactsSchema,
	type Import,
	type ImportedName,
	ImportedNameSchema,
	type ImportResolution,
	ImportResolutionSchema,
	ImportSchema,
	type IndexDepth,
	IndexDepthSchema,
	type Literal,
	LiteralSchema,
	type ProjectModel,
	ProjectModelSchema,
} from "./project.js";
export {
	type BlockedSite,
	type BlockedSiteReason,
	BlockedSiteReasonSchema,
	BlockedSiteSchema,
	RENAME_EDIT_CONFLICT,
	type RenameEditsRequest,
	RenameEditsRequestSchema,
	type RenameEditsResponse,
	RenameEditsResponseSchema,
	type RenameRefusal,
	RenameRefusalSchema,
	type RenameSite,
	RenameSiteSchema,
} from "./rename.js";
export {
	notImplementedBinding,
	notImplementedImport,
	notImplementedMove,
	notImplementedType,
	type ProviderHandlers,
	runProviderOnStdio,
	serveProvider,
} from "./serve.js";
export {
	composeSymbolId,
	type Descriptor,
	type DescriptorKind,
	decodeModuleField,
	encodeModuleField,
	expectIdSpace,
	isCanonicalModule,
	isLocalSymbol,
	isParameterSymbol,
	isSymbolId,
	isWithin,
	moduleOf,
	normalizeModulePath,
	ownerOf,
	parseSymbolId,
	parseSymbolIdResult,
	quoteName,
	readIdField,
	rebaseSymbolId,
	SYMBOL_SCHEME,
	type SymbolId,
} from "./symbolId.js";
export {
	type Declaration,
	DeclarationSchema,
	type Diagnostic,
	DiagnosticSchema,
	type Metrics,
	MetricsSchema,
	type Position,
	PositionSchema,
	type Range,
	RangeSchema,
	type Reference,
	ReferenceRoleSchema,
	ReferenceSchema,
	type SymbolKind,
	SymbolKindSchema,
	VisibilitySchema,
} from "./symbols.js";
export {
	type Binding,
	BindingSchema,
	isResolved,
	type Provenance,
	ProvenanceSchema,
	reasonOf,
	type TypeInfo,
	TypeInfoSchema,
	type UnknownReason,
	UnknownReasonSchema,
} from "./values.js";
export {
	type Compatibility,
	checkCompatibility,
	isCompatibleProtocol,
	PROTOCOL_VERSION,
	parseVersion,
	type Version,
} from "./version.js";
