// Writes providers/python/src/syntax/unicodeNameData.ts, the character names Python's `\N{...}`
// escape reads, from the Unicode Character Database.
//
//   bun scripts/unicodeNames.ts <UnicodeData.txt> <NameAliases.txt> <version>
//
// Both files come from https://www.unicode.org/Public/<version>/ucd/.

import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { deflateRawSync } from "node:zlib";

const [dataPath, aliasesPath, version] = process.argv.slice(2);
if (dataPath === undefined || aliasesPath === undefined || version === undefined) {
	console.error("usage: bun scripts/unicodeNames.ts <UnicodeData.txt> <NameAliases.txt> <version>");
	process.exit(2);
}

/** Ranges named by a prefix and the code point; the Hangul block is named from its jamo. */
const RANGE_PREFIXES: ReadonlyArray<readonly [string, string]> = [
	["CJK Ideograph", "CJK UNIFIED IDEOGRAPH-"],
	["Tangut Ideograph", "TANGUT IDEOGRAPH-"],
];

const lines: string[] = [];
const hexNamed: Array<[string, number, number]> = [];
let hangul: [number, number] | undefined;
let opened: { label: string; first: number } | undefined;

for (const row of readFileSync(dataPath, "utf8").split("\n")) {
	const [hex, name] = row.split(";");
	if (hex === undefined || name === undefined || hex === "") continue;
	const point = Number.parseInt(hex, 16);
	if (name.startsWith("<") && name.endsWith(", First>")) {
		opened = { label: name.slice(1, -", First>".length), first: point };
		continue;
	}
	if (name.startsWith("<") && name.endsWith(", Last>")) {
		if (opened === undefined) throw new Error(`a range closes unopened at ${hex}`);
		const { label, first } = opened;
		opened = undefined;
		if (label === "Hangul Syllable") hangul = [first, point];
		const prefix = RANGE_PREFIXES.find(([start]) => label.startsWith(start))?.[1];
		if (prefix !== undefined) hexNamed.push([prefix, first, point]);
		continue;
	}
	// `<control>` and the like name nothing; their aliases do.
	if (name.startsWith("<")) continue;
	lines.push(`${hex} ${name}`);
}

for (const row of readFileSync(aliasesPath, "utf8").split("\n")) {
	if (row.startsWith("#") || row.trim() === "") continue;
	const [hex, alias] = row.split(";");
	if (hex !== undefined && alias !== undefined) lines.push(`${hex} ${alias}`);
}

if (hangul === undefined) throw new Error("the database holds no Hangul syllable range");
const packed = deflateRawSync(Buffer.from(lines.join("\n"), "utf8"), { level: 9 }).toString("base64");
const ranges = hexNamed.map(
	([prefix, first, last]) => `\t["${prefix}", 0x${first.toString(16)}, 0x${last.toString(16)}],`,
);

const output = `// Generated by scripts/unicodeNames.ts from the Unicode Character Database ${version}. Do not edit.

/** Deflated lines of a hexadecimal code point and a name or an alias, in base64. */
export const NAMES =
	"${packed}";

/** Ranges whose names are a prefix and the code point in hexadecimal. */
export const HEX_NAMED: ReadonlyArray<readonly [string, number, number]> = [
${ranges.join("\n")}
];

/** The Hangul syllables, named from their jamo. */
export const HANGUL: readonly [number, number] = [0x${hangul[0].toString(16)}, 0x${hangul[1].toString(16)}];
`;

const target = path.join(import.meta.dir, "..", "providers", "python", "src", "syntax", "unicodeNameData.ts");
writeFileSync(target, output);
console.log(`${lines.length} names and aliases, ${hexNamed.length} ranges, ${packed.length} base64 characters`);
